#!/bin/bash
# 快速开始指南

echo "==================================="
echo "自动签到系统 - 快速使用指南"
echo "==================================="
echo ""
echo "1. 修改配置文件"
echo "   nano config/sites.yaml"
echo "   填入你的 anyrouter 账号和密码"
echo ""
echo "2. 测试运行"
echo "   python3 src/main.py --dry-run    # 测试配置"
echo "   python3 src/main.py --debug      # 调试模式(显示浏览器)"
echo "   python3 src/main.py              # 正式运行"
echo ""
echo "3. 设置定时任务"
echo "   crontab -e"
echo "   添加: 0 9 * * * $(pwd)/run.sh >> $(pwd)/logs/cron.log 2>&1"
echo ""
echo "4. 查看日志"
echo "   tail -f logs/checkin.log"
echo ""
echo "==================================="
